# Generated by Django 5.1.2 on 2024-11-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Ordering_App', '0003_category_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='Menu_Categories'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='Menu_Categories'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image'),
        ),
    ]
