# Generated by Django 5.1.2 on 2024-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Ordering_App', '0004_alter_category_image_alter_menu_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='delivery_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='quantity_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
