# Generated by Django 5.1.2 on 2024-12-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Food_Ordering_App", "0007_userprofile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("Driver", "DRIVER"), ("Customer", "CUSTOMER")],
                max_length=20,
                null=True,
            ),
        ),
    ]
